version: '3.4'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  api:
    build: .
    container_name: app.web
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/opt/app
    depends_on:
      - db
  web:
    image: nginx:1.17-alpine
    container_name: web.server
    ports:
      - 10080:80
    volumes:
      - .:/opt/app
      - ./logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    depends_on:
      - api
  app:
    build: ./
    container_name: web.app
    working_dir: /opt/app/src
    command: elm reactor
    volumes:
      - ./src:/opt/app/src
    ports:
      - '8000:8000'
    tty: true

  db:
    image: postgres
    container_name: app.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
    user: root
    ports:
      - "5432:5432"
    volumes:
      - app.db.volume:/var/lib/postgresql/data
    restart: always
