version: '3.7'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  api:
    build: ./Docker/Elixir
    container_name: web.app
    ports:
      - 4000:4000
      - 8000:8000
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/opt/app
    depends_on:
      - db
    tty: true

  server:
    image: nginx:1.17-alpine
    container_name: server.app
    ports:
      - 10080:80
    volumes:
      - .:/opt/app
      - ./logs:/var/log/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    tty: true
    depends_on:
      - api

  db:
    image: postgres
    container_name: db.app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - 54321:5432
    volumes:
      - app.db.volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis.app
    ports:
      - 6380:6379
    volumes:
      - ./redis:/redis