version: '3.7'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  api:
    build: ./Docker/Elixir
    container_name: api.app
    ports:
      - 4000:4000
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/opt/app
      - ./api:/opt/app/api
    depends_on:
      - db
    tty: true

  assets:
    build: ./Docker/Elm
    container_name: assets.app
    volumes:
      - .:/opt/app
      - ./assets:/opt/app/assets
    ports:
      - 8000:8000
    depends_on:
      - api
    tty: true

  server:
    image: nginx:1.17-alpine
    container_name: server.app
    ports:
      - 10080:80
    volumes:
      - .:/opt/app
      - ./logs:/var/log/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    tty: true
    depends_on:
      - api

  db:
    image: postgres
    container_name: db.app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - 5432:5432
    volumes:
      - app.db.volume:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
      - "./redis:/redis"