version: '3.4'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  app:
    build: .
    container_name: app.web
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/opt/app
    depends_on:
      - db

  front:
    build: ./elm
    container_name: 'elm_app'
    working_dir: /opt/app/elm
    volumes:
      - ./elm:/opt/app/elm
    ports:
      - '8000:8000'
    tty: true

  db:
    image: postgres
    container_name: app.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
    user: root
    ports:
      - "5432:5432"
    volumes:
      - app.db.volume:/var/lib/postgresql/data
    restart: always