version: '3.4'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  api:
    build: ./Docker/Elixir
    container_name: api.app
    ports:
      - 4000:4000
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./:/opt/app/
    depends_on:
      - db

  db:
    image: postgres
    container_name: db.app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - app.db.volume:/var/lib/postgresql/data

  server:
    image: nginx:1.17-alpine
    container_name: server.app
    ports:
      - 10080:80
    volumes:
      - .:/opt/app
      - ./logs:/var/log/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    tty: true
    depends_on:
      - api

  assets:
    build: ./Docker/Elm
    container_name: assets.app
    volumes:
      - ./assets:/opt/app/assets
    ports:
      - 8000:8000
    depends_on:
      - api
    tty: true
