version: '3.4'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  app:
    build: .
    container_name: app.web
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/opt/app
    depends_on:
      - db

  web:
    build: ./
    container_name: 'web_app'
    working_dir: /opt/app/web
    command: elm reactor
    volumes:
      - ./web:/opt/app/web
    ports:
      - '8000:8000'
    tty: true

  db:
    image: postgres
    container_name: app.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
    user: root
    ports:
      - "5432:5432"
    volumes:
      - app.db.volume:/var/lib/postgresql/data
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
        - 8080:80
    volumes:
        - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      - MIX_ENV=dev
      - PORT=8080
    hostname: pgadmin4
    depends_on:
        - db
    restart: always