version: '3.4'

volumes:
  app.db.volume:
    name: app.db.volume

services:
  api:
    build: Docker/Elixir
    container_name: app.web
    ports:
      - '4000:4000'
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./app.api.volume:/opt/app/api
    depends_on:
      - db
    tty: true
  web:
    image: nginx:1.17-alpine
    container_name: web.server
    ports:
      - 10080:80
    volumes:
      - .:/opt/app
      - ./logs:/var/log/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    tty: true
    depends_on:
      - api
  app:
    build: ./Docker/Elm
    container_name: web.app
    volumes:
      - ./app.web.volume:/opt/app/assets
    ports:
      - '8000:8000'
    depends_on:
      - api
    tty: true

  db:
    image: postgres
    container_name: app.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
    user: root
    ports:
      - '5432:5432'
    volumes:
      - ./app.db.volume:/var/lib/postgresql/data
    restart: always
